version: "3.8"
services:
  node:
    build: .
    container_name: fluentws_node
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: yarn start-dev

  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
    ports:
      - "9880:9880"
    depends_on:
      - node
